name: Deploy Backend

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r minimal_requirements.txt
    
    - name: Run tests with environment variables
      env:
        FIREBASE_TYPE: ${{ secrets.FIREBASE_TYPE }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
        FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
        FIREBASE_CLIENT_ID: ${{ secrets.FIREBASE_CLIENT_ID }}
        FIREBASE_AUTH_URI: ${{ secrets.FIREBASE_AUTH_URI }}
        FIREBASE_TOKEN_URI: ${{ secrets.FIREBASE_TOKEN_URI }}
        FIREBASE_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.FIREBASE_AUTH_PROVIDER_X509_CERT_URL }}
        FIREBASE_CLIENT_X509_CERT_URL: ${{ secrets.FIREBASE_CLIENT_X509_CERT_URL }}
        FIREBASE_UNIVERSE_DOMAIN: ${{ secrets.FIREBASE_UNIVERSE_DOMAIN }}
        USE_FIRESTORE: true
        API_HOST: 0.0.0.0
        API_PORT: 8000
        ALLOWED_ORIGINS: http://localhost:3000
      run: |
        python -c "from app.services.firestore_service import FirestoreService; fs = FirestoreService(); print('Firestore connection successful')"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r minimal_requirements.txt
    
    - name: Deploy to server
      env:
        FIREBASE_TYPE: ${{ secrets.FIREBASE_TYPE }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
        FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
        FIREBASE_CLIENT_ID: ${{ secrets.FIREBASE_CLIENT_ID }}
        FIREBASE_AUTH_URI: ${{ secrets.FIREBASE_AUTH_URI }}
        FIREBASE_TOKEN_URI: ${{ secrets.FIREBASE_TOKEN_URI }}
        FIREBASE_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.FIREBASE_AUTH_PROVIDER_X509_CERT_URL }}
        FIREBASE_CLIENT_X509_CERT_URL: ${{ secrets.FIREBASE_CLIENT_X509_CERT_URL }}
        FIREBASE_UNIVERSE_DOMAIN: ${{ secrets.FIREBASE_UNIVERSE_DOMAIN }}
        USE_FIRESTORE: true
        API_HOST: ${{ secrets.API_HOST || '0.0.0.0' }}
        API_PORT: ${{ secrets.API_PORT || '8000' }}
        ALLOWED_ORIGINS: ${{ secrets.ALLOWED_ORIGINS || 'http://localhost:3000' }}
      run: |
        echo "Deploying with environment variables from GitHub Secrets"
        # Add your deployment commands here
        # For example: docker build, deploy to cloud platform, etc. 